baseURL = "https://aaltomcc.github.io/cs-ej4101-fall-2019-008-advanced/"
languageCode = "en-us"
title = "cs-ej4101-fall-2019-008-advanced"
theme = "hugo-goa"

## Site Settings
[params]
dateformat = "Jan 2, 2006"
## Main Menu
[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "posts"
    weight = 2
    identifier = "posts"
    url = "/posts/"

## Extras
[params.extra]
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false
